system:
  mode: 1 # 0 for graph mode, 1 for pynative mode in MindSpore
  distribute: False 
  amp_level: 'O0'
  seed: 42

common:
  character_dict_path: &character_dict_path mindocr/utils/dict/en_dict.txt
  num_classes: &num_classes 64 # TODO: retreive this value from dictionary
  max_text_length: &max_text_length 23
  infer_mode: &infer_mode False
  use_space_char: &use_space_char False
  batch_size: &batch_size 32

model:
  type: rec
  transform: null
  backbone:
    name: rec_vgg7 #resnet34@mindcv
    pretrained: False
  neck:
    name: RNNEncoder
    hidden_size: 256 
  head:
    name: CTCHead 
    out_channels: *num_classes 

loss:
  name: CTCLoss 
  pred_seq_len: 24 # TODO: this should be probed from the network output.
  max_label_length: *max_text_length  # this value should be smaller than pre_seq_len
  batch_size: *batch_size

scheduler: 
  scheduler: "cosine_decay"
  min_lr: 0.000001
  lr: 0.001
  num_epochs: 300
  warmup_epochs: 10
  decay_epochs: 280

optimizer:
  opt: "momentum"
  filter_bias_and_bn: True
  momentum: 0.9
  weight_decay: 0.0001
  loss_scale: 1.0
  use_nesterov: True 

train:
  dataset_sink_mode: False
  dataset:
    type: RecDataset
    #data_dir: /Users/Samit/Data/datasets/ic15/rec/ch4_training_word_images_gt
    #label_files: /Users/Samit/Data/datasets/ic15/rec/rec_gt_train.txt
    data_dir: /data/ocr_datasets/ic15/word_recognition/ch4_training_word_images_gt
    label_files: /data/ocr_datasets/ic15/word_recognition/rec_gt_train.txt
    sample_ratios: [1.0]
    shuffle: True
    transform_pipeline:
      - DecodeImage: 
          img_mode: BGR
          to_float32: False
      - CTCLabelEncode: 
          max_text_length: *max_text_length 
          character_dict_path: *character_dict_path
          use_space_char: *use_space_char
      - RecResizeImg: # different from paddle (paddle converts image from HWC to CHW and rescale to [-1, 1] after resize. 
          image_shape: [32, 100] # H, W
          infer_mode: *infer_mode
          character_dict_path: *character_dict_path
          padding: True # aspect ratio will be preserved if true.
      - NormalizeImage:  # different from paddle (paddle wrongly normalize BGR image with RGB mean/std from ImageNet for det, and simple rescale to [-1, 1] in rec. 
          bgr_to_rgb: True
          is_hwc: True
          mean : [127.0, 127.0, 127.0] 
          std : [127.0, 127.0, 127.0]
      - ToCHWImage: 
    #  the order of the dataloader list, matching the network input and the input labels for the loss function, and optional data for debug/visaulize 
    output_keys: ['image', 'label'] #, 'length'] #'img_path'] 
    num_keys_to_net: 1 # num inputs for network forward func
    #keys_for_loss: 4 # num labels for loss func
     
  loader:
      shuffle: True # TODO: tbc
      batch_size: *batch_size
      drop_remainder: True
      max_rowsize: 6
      num_workers: 2
