model:
  type: det
  transform: null
  backbone:
    name: det_resnet50
    pretrained: False
  neck:
    name: FPN
    out_channels: 256
    #use_asf: True
  head:
    name: ConvHead 
    out_channels: 2
    k: 50

scheduler: 
  name: "cosine_decay"
  min_lr: 0.0
  lr: 0.1
  warmup_epochs: 4
  decay_epochs: 96

optimizer:
  name: "momentum"
  filter_bias_and_bn: True
  momentum: 0.9
  weight_decay: 0.0001
  loss_scale: 1024
  use_nesterov: False

train:
  dataset:
    type: DetDataset
    data_dir: /data/ocr_datasets/ic15/text_localization/train
    label_files: /data/ocr_datasets/ic15/text_localization/train/train_icdar15_label.txt
    sample_ratios: [1.0]
    shuffle: True,
    transform_pipeline:
              - DecodeImage: 
                  img_mode: BGR, 
                  to_float32: False
              - DetLabelEncode:  
              - MZResizeByGrid: 
                  #denominator: 32
                  divisor: 32
                  transform_polys: True # originally in modelzoo, it doesn't transform polys
              - MZRandomScaleByShortSide: 
                  short_side: 736
              - IaaAugment: 
                  augmenter_args:
                    - {'type': 'Affine', 'args': {'rotate': [-10, 10]}}
                    - {'type': 'Fliplr', 'args': {'p': 0.5}}
              - MZRandomCropData: 
                  max_tries: 100 
                  min_crop_side_ratio: 0.1
                  crop_size: [640, 640]
              - MZResizeByGrid: 
                  #denominator: 32
                  divisor: 32
                  transform_polys: True
              #- MakeShrinkMap: 
              - MZMakeSegDetectionData: 
                  min_text_size: 8
                  shrink_ratio: 0.4
              #- 'MakeBorderMap': 
              - MZMakeBorderMap:
                  shrink_ratio: 0.4
                  thresh_min: 0.3
                  thresh_max: 0.7
              - MZRandomColorAdjust: 
                  brightness: 32.0 / 255
                  saturation: 0.5
                  to_numpy: True
              #{'MZIrregularNormToCHW': None},
              - NormalizeImage: 
                  bgr_to_rgb: True
                  is_hwc: True
                  mean : [123.675, 116.28, 103.53]
                  std : [58.395, 57.12, 57.375]
              - ToCHWImage: 
    output_keys: ['img_path', 'image']
  loader:
      shuffle: True # TODO: tbc
      batch_size: 8
      drop_remainder: True
      max_rowsize: 6
      num_workers: 4
